//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capstone.Application.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Applicant created successfully..
        /// </summary>
        internal static string invalid_email_format
        {
            get
            {
                return ResourceManager.GetString("invalid_email_format", resourceCulture);
            }
        }
        internal static string invalid_phone_number_format
        {
            get
            {
                return ResourceManager.GetString("invalid_phone_number_format", resourceCulture);
            }
        }
        internal static string user_not_found
        {
            get
            {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
        internal static string role_not_found
        {
            get
            {
                return ResourceManager.GetString("role_not_found", resourceCulture);
            }
        }
        internal static string user_already_has_role
        {
            get
            {
                return ResourceManager.GetString("user_already_has_role", resourceCulture);
            }
        }
        internal static string invalid_token
        {
            get
            {
                return ResourceManager.GetString("invalid_token", resourceCulture);
            }
        }
        internal static string old_password_not_correct
        {
            get
            {
                return ResourceManager.GetString("old_password_not_correct", resourceCulture);
            }
        }
        internal static string role_name_empty
        {
            get
            {
                return ResourceManager.GetString("role_name_empty", resourceCulture);
            }
        }

        internal static string description_empty
        {
            get
            {
                return ResourceManager.GetString("description_empty", resourceCulture);
            }
        }
        internal static string color_empty
        {
            get
            {
                return ResourceManager.GetString("color_empty", resourceCulture);
            }
        }
        internal static string list_permission_empty
        {
            get
            {
                return ResourceManager.GetString("list_permission_empty", resourceCulture);
            }
        }
        internal static string role_already_exists
        {
            get
            {
                return ResourceManager.GetString("role_already_exists", resourceCulture);
            }
        }
        internal static string failed_to_create_role
        {
            get
            {
                return ResourceManager.GetString("failed_to_create_role", resourceCulture);
            }
        }

        internal static string delete_fail
        {
            get
            {
                return ResourceManager.GetString("delete_fail", resourceCulture);
            }
        }
        internal static string account_with_email_exists
        {
            get
            {
                return ResourceManager.GetString("account_with_email_exists", resourceCulture);
            }
        }
        internal static string username_already_exists
        {
            get
            {
                return ResourceManager.GetString("username_already_exists", resourceCulture);
            }
        }
        internal static string user_creation_failed
        {
            get
            {
                return ResourceManager.GetString("user_creation_failed", resourceCulture);
            }
        }
        internal static string password_null_or_empty
        {
            get
            {
                return ResourceManager.GetString("password_null_or_empty", resourceCulture);
            }
        }
        internal static string code_null_or_empty
        {
            get
            {
                return ResourceManager.GetString("code_null_or_empty", resourceCulture);
            }
        }
        internal static string code_already_used
        {
            get
            {
                return ResourceManager.GetString("code_already_used", resourceCulture);
            }
        }
        internal static string something_wrong
        {
            get
            {
                return ResourceManager.GetString("something_wrong", resourceCulture);
            }
        }
        internal static string reset_password_code_expired_or_incorrect
        {
            get
            {
                return ResourceManager.GetString("reset_password_code_expired_or_incorrect", resourceCulture);
            }
        }
        internal static string project_not_found
        {
            get
            {
                return ResourceManager.GetString("project_not_found", resourceCulture);
            }
        }

        internal static string code_expired_or_wrong
        {
            get
            {
                return ResourceManager.GetString("code_expired_or_wrong", resourceCulture);
            }
        }
        internal static string email_empty
        {
            get
            {
                return ResourceManager.GetString("email_empty", resourceCulture);
            }
        }
        internal static string check_email_for_instruction
        {
            get
            {
                return ResourceManager.GetString("check_email_for_instruction", resourceCulture);
            }
        }
        internal static string message_already_sent
        {
            get
            {
                return ResourceManager.GetString("message_already_sent", resourceCulture);
            }
        }
        internal static string permission_name_empty
        {
            get
            {
                return ResourceManager.GetString("permission_name_empty", resourceCulture);
            }
        }
        internal static string permission_not_found
        {
            get
            {
                return ResourceManager.GetString("permission_not_found", resourceCulture);
            }
        }
        internal static string invalid_google_token
        {
            get
            {
                return ResourceManager.GetString("invalid_google_token", resourceCulture);
            }
        }
        internal static string account_not_found
        {
            get
            {
                return ResourceManager.GetString("account_not_found", resourceCulture);
            }
        }
        internal static string password_not_correct
        {
            get
            {
                return ResourceManager.GetString("password_not_correct", resourceCulture);
            }
        }
        internal static string token_required
        {
            get
            {
                return ResourceManager.GetString("token_required", resourceCulture);
            }
        }
        internal static string error_processing_request
        {
            get
            {
                return ResourceManager.GetString("error_processing_request", resourceCulture);
            }
        }
        internal static string account_inactive
        {
            get
            {
                return ResourceManager.GetString("account_inactive", resourceCulture);
            }
        }
        internal static string invalid_refresh_token
        {
            get
            {
                return ResourceManager.GetString("invalid_refresh_token", resourceCulture);
            }
        }
        internal static string refresh_token_expired
        {
            get
            {
                return ResourceManager.GetString("refresh_token_expired", resourceCulture);
            }
        }
        internal static string token_validation_failed
        {
            get
            {
                return ResourceManager.GetString("token_validation_failed", resourceCulture);
            }
        }
        internal static string title_empty
        {
            get
            {
                return ResourceManager.GetString("title_empty", resourceCulture);
            }
        }
        internal static string title_label_available
        {
            get
            {
                return ResourceManager.GetString("title_label_available", resourceCulture);
            }
        }
        internal static string cannot_delete_all_default_labels
        {
            get
            {
                return ResourceManager.GetString("cannot_delete_all_default_labels", resourceCulture);
            }
        }
        internal static string label_not_found
        {
            get
            {
                return ResourceManager.GetString("label_not_found", resourceCulture);
            }
        }
        internal static string label_id_null
        {
            get
            {
                return ResourceManager.GetString("label_id_null", resourceCulture);
            }
        }
        internal static string name_empty
        {
            get
            {
                return ResourceManager.GetString("name_empty", resourceCulture);
            }
        }
        internal static string group_permission_exists
        {
            get
            {
                return ResourceManager.GetString("group_permission_exists", resourceCulture);
            }
        }
        internal static string group_permission_not_found
        {
            get
            {
                return ResourceManager.GetString("group_permission_not_found", resourceCulture);
            }
        }
        internal static string permission_exists
        {
            get
            {
                return ResourceManager.GetString("permission_exists", resourceCulture);
            }
        }
        internal static string no_more_phase
        {
            get
            {
                return ResourceManager.GetString("no_more_phase", resourceCulture);
            }
        }
        internal static string project_no_phase
        {
            get
            {
                return ResourceManager.GetString("project_no_phase", resourceCulture);
            }
        }
        internal static string title_phase_available
        {
            get
            {
                return ResourceManager.GetString("title_phase_available", resourceCulture);
            }
        }
        internal static string end_date_greater_than_start_date
        {
            get
            {
                return ResourceManager.GetString("end_date_greater_than_start_date", resourceCulture);
            }
        }
        internal static string start_date_greater_than_phases
        {
            get
            {
                return ResourceManager.GetString("start_date_greater_than_phases", resourceCulture);
            }
        }
        internal static string phase_not_found
        {
            get
            {
                return ResourceManager.GetString("phase_not_found", resourceCulture);
            }
        }
        internal static string phase_running_or_completed
        {
            get
            {
                return ResourceManager.GetString("phase_running_or_completed", resourceCulture);
            }
        }
        internal static string phase_done
        {
            get
            {
                return ResourceManager.GetString("phase_done", resourceCulture);
            }
        }
        internal static string title_available
        {
            get
            {
                return ResourceManager.GetString("title_available", resourceCulture);
            }
        }
        internal static string skills_not_found
        {
            get
            {
                return ResourceManager.GetString("skills_not_found", resourceCulture);
            }
        }
        internal static string skills_already_exist_for_user
        {
            get
            {
                return ResourceManager.GetString("skills_already_exist_for_user", resourceCulture);
            }
        }
        internal static string skill_title_empty_or_null
        {
            get
            {
                return ResourceManager.GetString("skill_title_empty_or_null", resourceCulture);
            }
        }
        internal static string member_not_found
        {
            get
            {
                return ResourceManager.GetString("member_not_found", resourceCulture);
            }
        }
        internal static string project_code_exists
        {
            get
            {
                return ResourceManager.GetString("project_code_exists", resourceCulture);
            }
        }
        internal static string team_lead_not_found
        {
            get
            {
                return ResourceManager.GetString("team_lead_not_found", resourceCulture);
            }
        }
        internal static string file_content_cannot_be_null
        {
            get
            {
                return ResourceManager.GetString("file_content_cannot_be_null", resourceCulture);
            }
        }
        internal static string position_not_found
        {
            get
            {
                return ResourceManager.GetString("position_not_found", resourceCulture);
            }
        }
        internal static string status_not_valid
        {
            get
            {
                return ResourceManager.GetString("status_not_valid", resourceCulture);
            }
        }

        internal static string total_members_need_at_least_1
        {
            get
            {
                return ResourceManager.GetString("total_members_need_at_least_1", resourceCulture);
            }
        }

        internal static string notification_not_found
        {
            get
            {
                return ResourceManager.GetString("notification_not_found", resourceCulture);
            }
        }

        internal static string user_no_permission_delete_notification
        {
            get
            {
                return ResourceManager.GetString("user_no_permission_delete_notification", resourceCulture);
            }
        }
        internal static string priority_range
        {
            get
            {
                return ResourceManager.GetString("priority_range", resourceCulture);
            }
        }
        internal static string estimated_time_greater_than_zero
        {
            get
            {
                return ResourceManager.GetString("estimated_time_greater_than_zero", resourceCulture);
            }
        }
        internal static string parent_issue_not_found
        {
            get
            {
                return ResourceManager.GetString("parent_issue_not_found", resourceCulture);
            }
        }
        internal static string percentage_range
        {
            get
            {
                return ResourceManager.GetString("percentage_range", resourceCulture);
            }
        }
    }
}
