using Capstone.Domain.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Capstone.Application.Common.EmailHTML
{
    public static class  EmailMessage
    {
        public static string AssignLeader(string projectName, string leadName, Guid projectId)
        {
            return $"<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Project Created Email</title>\r\n    <style>\r\n        body {{\r\n            font-family: Arial, sans-serif;\r\n            line-height: 1.6;\r\n            margin: 0;\r\n            padding: 0;\r\n            background-color: #f9f9f9;\r\n            color: #333;\r\n        }}\r\n        .email-container {{\r\n            max-width: 600px;\r\n            margin: 20px auto;\r\n            padding: 20px;\r\n            background-color: #ffffff;\r\n            border: 1px solid #ddd;\r\n            border-radius: 5px;\r\n            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n        }}\r\n        h1 {{\r\n            font-size: 20px;\r\n            color: #444;\r\n        }}\r\n        p {{\r\n            margin: 10px 0;\r\n        }}\r\n        .button-container {{\r\n            margin: 20px 0;\r\n            text-align: center;\r\n        }}\r\n        .button {{\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            background-color: #007bff;\r\n            color: #fff;\r\n            text-decoration: none;\r\n            border-radius: 5px;\r\n            font-size: 16px;\r\n            font-weight: bold;\r\n        }}\r\n        .button:hover {{\r\n            background-color: #0056b3;\r\n        }}\r\n        footer {{\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            text-align: center;\r\n            color: #888;\r\n        }}\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"email-container\">\r\n        <h1>Hello {leadName},</h1>\r\n        <p>We’re pleased to let you know that <strong>{projectName}</strong> has been created, and you are now assigned as the project leader.</p>\r\n        <p>You have full access to manage this project, coordinate with the team, and set priorities to move forward.</p>\r\n        <h2>Next Steps</h2>\r\n        <p>To get started, review the project’s details and set up initial issues and goals.</p>\r\n        <div class=\"button-container\">\r\n            <a href=\"https://headnshoulder.netlify.app/projects/{projectId}?tab=overview\" class=\"button\">Go to Project Details</a>\r\n        </div>\r\n        <p>If you need any help or have questions, feel free to reach out.</p>\r\n \r\n    </div>\r\n</body>\r\n</html>";
        }

        public static string AssignMember(string projectName, string userName, string projectDescription, Guid projectId)
        {
            return $"<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Project Created Email</title>\r\n    <style>\r\n        body {{\r\n            font-family: Arial, sans-serif;\r\n            line-height: 1.6;\r\n            margin: 0;\r\n            padding: 0;\r\n            background-color: #f9f9f9;\r\n            color: #333;\r\n        }}\r\n        .email-container {{\r\n            max-width: 600px;\r\n            margin: 20px auto;\r\n            padding: 20px;\r\n            background-color: #ffffff;\r\n            border: 1px solid #ddd;\r\n            border-radius: 5px;\r\n            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n        }}\r\n        h1 {{\r\n            font-size: 20px;\r\n            color: #444;\r\n        }}\r\n        p {{\r\n            margin: 10px 0;\r\n        }}\r\n        .button-container {{\r\n            margin: 20px 0;\r\n            text-align: center;\r\n        }}\r\n        .button {{\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            background-color: #007bff;\r\n            color: #fff;\r\n            text-decoration: none;\r\n            border-radius: 5px;\r\n            font-size: 16px;\r\n            font-weight: bold;\r\n        }}\r\n        .button:hover {{\r\n            background-color: #0056b3;\r\n        }}\r\n        footer {{\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            text-align: center;\r\n            color: #888;\r\n        }}\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"email-container\">\r\n        <h1>Hello {userName},</h1>\r\n        <p>You’ve been added to the <strong>{projectName}</strong>  team! We’re excited to have you on board.</p>\r\n        <p>Project Overview: This project focuses on {projectDescription}. As a team member, you’ll contribute to achieving these goals by collaborating closely with your project leader</p>\r\n        <h2>Next Steps</h2>\r\n        <p>Review Project Details: Familiarize yourself with the project scope, timelines, and current issues.</p>\r\n  <p>Connect with the Team: Reach out to your project leader or other team members if you have any questions.</p>\r\n         <div class=\"button-container\">\r\n            <a href=\"https://headnshoulder.netlify.app/projects/{projectId}?tab=kanban\" class=\"button\">Go to Project Details</a>\r\n        </div>\r\n        <p>If you need any help or have questions, feel free to reach out.</p>\r\n \r\n    </div>\r\n</body>\r\n</html>";
        }

        public static string AssignIssue(string name, string? description, DateTime? startDate, DateTime? dueDate, string issueId, string projectId)
        {
            return $"<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Project Created Email</title>\r\n    <style>\r\n        body {{\r\n            font-family: Arial, sans-serif;\r\n            line-height: 1.6;\r\n            margin: 0;\r\n            padding: 0;\r\n            background-color: #f9f9f9;\r\n            color: #333;\r\n        }}\r\n        .email-container {{\r\n            max-width: 600px;\r\n            margin: 20px auto;\r\n            padding: 20px;\r\n            background-color: #ffffff;\r\n            border: 1px solid #ddd;\r\n            border-radius: 5px;\r\n            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n        }}\r\n        h1 {{\r\n            font-size: 20px;\r\n            color: #444;\r\n        }}\r\n        p {{\r\n            margin: 10px 0;\r\n        }}\r\n        .button-container {{\r\n            margin: 20px 0;\r\n            text-align: center;\r\n        }}\r\n        .button {{\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            background-color: #007bff;\r\n            color: #fff;\r\n            text-decoration: none;\r\n            border-radius: 5px;\r\n            font-size: 16px;\r\n            font-weight: bold;\r\n        }}\r\n        .button:hover {{\r\n            background-color: #0056b3;\r\n        }}\r\n        footer {{\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            text-align: center;\r\n            color: #888;\r\n        }}\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"email-container\">\r\n    <p>You have been assigned a new issue: {name}.</p>\r\n        <p>issue Details:</p>\r\n <p>Description: {description}</p>\r\n     <p>Start Date: {startDate}</p>\r\n    <p>Due Date: {dueDate}</p>\r\n          <h2>Next Steps</h2>\r\n        <p>Please review the issue details, start planning your approach, and reach out if you have any questions or need further clarification.</p>\r\n   <div class=\"button-container\">\r\n            <a href=\"https://headnshoulder.netlify.app/projects/{projectId}/issues/{issueId}\" class=\"button\">Go to issue Details</a>\r\n        </div>\r\n        <p>If you need any help or have questions, feel free to reach out.</p>\r\n \r\n    </div>\r\n</body>\r\n</html>";
        }

        public static string CreateComment(string name, string issueId, string projectId)
        {
            return $"<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Project Created Email</title>\r\n    <style>\r\n        body {{\r\n            font-family: Arial, sans-serif;\r\n            line-height: 1.6;\r\n            margin: 0;\r\n            padding: 0;\r\n            background-color: #f9f9f9;\r\n            color: #333;\r\n        }}\r\n        .email-container {{\r\n            max-width: 600px;\r\n            margin: 20px auto;\r\n            padding: 20px;\r\n            background-color: #ffffff;\r\n            border: 1px solid #ddd;\r\n            border-radius: 5px;\r\n            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n        }}\r\n        h1 {{\r\n            font-size: 20px;\r\n            color: #444;\r\n        }}\r\n        p {{\r\n            margin: 10px 0;\r\n        }}\r\n        .button-container {{\r\n            margin: 20px 0;\r\n            text-align: center;\r\n        }}\r\n        .button {{\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            background-color: #007bff;\r\n            color: #fff;\r\n            text-decoration: none;\r\n            border-radius: 5px;\r\n            font-size: 16px;\r\n            font-weight: bold;\r\n        }}\r\n        .button:hover {{\r\n            background-color: #0056b3;\r\n        }}\r\n        footer {{\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            text-align: center;\r\n            color: #888;\r\n        }}\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"email-container\">\r\n    <p>You have a new or update comment on issue: {name}.</p>\r\n      <div class=\"button-container\">\r\n            <a href=\"https://headnshoulder.netlify.app/projects/{projectId}/issues/{issueId}\" class=\"button\">Go to issue Details</a>\r\n        </div>\r\n        <p>If you need any help or have questions, feel free to reach out.</p>\r\n \r\n    </div>\r\n</body>\r\n</html>";
        }

        public static string UpdateIssue(string name, string issueId, string projectId)
        {
            return $"<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n    <title>Project Created Email</title>\r\n    <style>\r\n        body {{\r\n            font-family: Arial, sans-serif;\r\n            line-height: 1.6;\r\n            margin: 0;\r\n            padding: 0;\r\n            background-color: #f9f9f9;\r\n            color: #333;\r\n        }}\r\n        .email-container {{\r\n            max-width: 600px;\r\n            margin: 20px auto;\r\n            padding: 20px;\r\n            background-color: #ffffff;\r\n            border: 1px solid #ddd;\r\n            border-radius: 5px;\r\n            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n        }}\r\n        h1 {{\r\n            font-size: 20px;\r\n            color: #444;\r\n        }}\r\n        p {{\r\n            margin: 10px 0;\r\n        }}\r\n        .button-container {{\r\n            margin: 20px 0;\r\n            text-align: center;\r\n        }}\r\n        .button {{\r\n            display: inline-block;\r\n            padding: 10px 20px;\r\n            background-color: #007bff;\r\n            color: #fff;\r\n            text-decoration: none;\r\n            border-radius: 5px;\r\n            font-size: 16px;\r\n            font-weight: bold;\r\n        }}\r\n        .button:hover {{\r\n            background-color: #0056b3;\r\n        }}\r\n        footer {{\r\n            margin-top: 20px;\r\n            font-size: 12px;\r\n            text-align: center;\r\n            color: #888;\r\n        }}\r\n    </style>\r\n</head>\r\n<body>\r\n    <div class=\"email-container\">\r\n    <p>Update on issue: {name}.</p>\r\n      <div class=\"button-container\">\r\n            <a href=\"https://headnshoulder.netlify.app/projects/{projectId}/issues/{issueId}\" class=\"button\">Go to issue Details</a>\r\n        </div>\r\n        <p>If you need any help or have questions, feel free to reach out.</p>\r\n \r\n    </div>\r\n</body>\r\n</html>";
        }
    }
}
